// Dashboard/src/routes/(auth)/footer.svelte

<footer>
    <span>© 2023</span>
    <p>
        Made by 
            <a href="https://parallax-stencuk.pages.dev/">Alexandr Stenčuk</a>
    </p>
</footer>

<style>
    footer {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        background-color: #f5f5f5;
        height: 100px;
        width: 100%;
        font-size: 14px;
        color: #333;
    }

    span {
        font-size: 12px;
        color: #999;
    }

    a {
        color: #333;
    }
    
    p {
        margin: 0;
    }

</style>

// client-next/src/app/footer.tsx
import React from "react";

export default function Footer(): React.ReactElement {
  return (
    <footer className="bg-body-tertiary text-center text-lg-start">
      <div className="text-center p-i3 footer_bgC">
        © 2023
        <a className="text-dark" href="https://parallax-stencuk.pages.dev/">
          Alexandr Stenčuk
        </a>
      </div>
    </footer>
  );
}
