// Dashboard/src/routes/(auth)/footer.svelte

<footer>
    <span>© 2023</span>
    <p>
        Made by 
            <a href="https://parallax-stencuk.pages.dev/">Alexandr Stenčuk</a>
    </p>
</footer>

<style>
    footer {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        background-color: #f5f5f5;
        height: 100px;
        width: 100%;
        font-size: 14px;
        color: #333;
    }

    span {
        font-size: 12px;
        color: #999;
    }

    a {
        color: #333;
    }
    
    p {
        margin: 0;
    }

</style>

// client/src/Pages/Footer.tsx

export default function Footer(): React.ReactElement {
    return (
        <footer className="bg-body-tertiary text-center text-lg-start">
            <div className="text-center p-3" style={{backgroundColor: "rgba(0, 0, 0, 0.2)"}}>
                © 2023
                <a className="text-dark" href="https://parallax-stencuk.pages.dev/">Alexandr Stenčuk</a>
            </div>
        </footer>
    )
}
